# required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Build documentation in the doc/src directory with Sphinx
sphinx:
   configuration: doc/src/conf.py

# declare Python requirements required to build docs
python:
   install:
   - requirements: doc/requirements.txt
