name: release

on:
  push:

jobs:

  build-linux-wheels:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@master

    - name: Install unixODBC development package
      run: yum install -y unixODBC-devel

    - name: Build wheel for Python 3.6
      run: /opt/python/cp36-cp36m/bin/python3.6 setup.py bdist_wheel

    - name: Build wheel for Python 3.7
      run: /opt/python/cp37-cp37m/bin/python3.7 setup.py bdist_wheel

    - name: Build wheel for Python 3.8
      run: /opt/python/cp38-cp38/bin/python3.8 setup.py bdist_wheel

    - name: Build wheel for Python 3.9
      run: /opt/python/cp39-cp39/bin/python3.9 setup.py bdist_wheel

    - name: Apply auditwheel for built wheels
      run: find . -name '*.whl' -exec auditwheel repair {} \; -print

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: wheelhouse
        path: dist
